---
title: "animated bubble plot"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(gganimate)
library(tidyverse)
```

```{r}
hr <- read_csv('./kaggle_hr_analytics.csv') %>% 
  mutate(salary = factor(salary, levels = c('low', 'medium', 'high'))) %>% 
  rename(department =  sales) %>% 
  mutate(department = fct_infreq(department)) %>% 
  mutate(number_project2 = number_project^2)
```

```{r}
d <- hr %>% 
  group_by(salary, time_spend_company) %>% 
  summarize(satisfaction_level = mean(satisfaction_level),
            last_evaluation = mean(last_evaluation),
            number_project = mean(number_project), 
            count = n()) %>% 
  ungroup() %>% 
  rename(tenure = time_spend_company) %>% 
  arrange(salary, desc(tenure)) %>% 
  mutate(past_satisfaction_level = lag(satisfaction_level),
         past_last_evaluation = lag(last_evaluation),
         past_salary = lag(salary)) %>% 
  mutate(past_satisfaction_level = ifelse(salary == past_salary, 
                                          past_satisfaction_level, NA)) %>% 
  mutate(past_last_evaluation = ifelse(salary == past_salary, 
                                          past_last_evaluation, NA))
```


```{r}
ggplot(d) +
  # geom_point(color = 'white', shape = 21,
  #            aes(x = satisfaction_level, 
  #                y = last_evaluation, 
  #                size = count, fill = salary)) +
  geom_text(aes(x = satisfaction_level,
                 y = last_evaluation,label = tenure), 
            hjust = 0, nudge_x = 0.01) +
  geom_segment(aes(x = satisfaction_level, y = last_evaluation, 
                   xend = past_satisfaction_level,
                   yend = past_last_evaluation),
               arrow = arrow(length = unit(0.2,"cm"))) +
  facet_wrap(~ salary, nrow = 1) +
  theme_minimal()

```


