---
title: "radar chart"
output: 
  html_document: 
    theme: flat
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list=ls())
gc()

library(tidyverse)
```

```{r}
hr <- read_csv('./kaggle_hr_analytics.csv') %>% 
  mutate(salary = case_when(salary == "low" ~ 1,
                            salary == "medium" ~ 2,
                            salary == "high" ~ 3)) %>% 
  rename(department =  sales) %>% 
  mutate(department = fct_infreq(department))
```

# Radar Chart

```{r}
library(fmsb)

d <- hr %>% 
  group_by(left) %>% 
  summarize(satisfaction_level = mean(satisfaction_level),
            last_evaluation = mean(last_evaluation),
            number_project = mean(number_project),
            average_montly_hours = mean(average_montly_hours),
            time_spend_company = mean(time_spend_company)) %>% 
  mutate(left = ifelse(left == 1, 'Left', 'Stayed'))

d_max <- hr %>% 
  select(one_of(c('satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company'))) %>% 
  summarize_all(max) %>% 
  mutate(left = 'max')
d_min <- hr %>% 
  select(one_of(c('satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company'))) %>% 
  summarize_all(min) %>% 
  mutate(left = 'min')

d <- bind_rows(d_max, d_min, d) %>% 
  as.data.frame

rownames(d) <- d$left
d$left <- NULL

radarchart(d, axistype = 0, 
           plwd = 3, plty = 1,
           cglcol="grey", cglty=1, axislabcol="grey", cglwd=0.8,
           vlcex=0.8)
```

# Plotly parallel coordinates

```{r}
library(plotly)
d <- read.csv("https://raw.githubusercontent.com/bcdunbar/datasets/master/iris.csv")
fig <- d %>% plot_ly(type = 'parcoords',
          line = list(color = ~species_id,
                      colorscale = list(c(0,'red'),c(0.5,'green'),c(1,'blue'))),
          dimensions = list(
            list(range = c(2,4.5),
                 label = 'Sepal Width', values = ~sepal_width),
            list(range = c(4,8),
                 constraintrange = c(5,6),
                 label = 'Sepal Length', values = ~sepal_length),
            list(range = c(0,2.5),
                 label = 'Petal Width', values = ~petal_width),
            list(range = c(1,7),
                 label = 'Petal Length', values = ~petal_length)
            )
          )

fig

```

```{r}
d <- sample_frac(hr, size = .5)

fig <- hr %>% 
  plot_ly(type = 'parcoords',
          line = list(color = ~left,
                      colorscale = list(c(0,'#0b718a'),c(1,'#e0b489'))),
          dimensions = list(
            list(range = c(0,1),
                 label = 'Left', values = ~left),
            list(range = c(0,1),
                 label = 'Job Satisfaction', values = ~satisfaction_level),
            list(range = c(0.36,1),
                 label = 'Last Evaluation', values = ~last_evaluation),
            list(range = c(2,10),
                 label = 'Tenure', values = ~time_spend_company),
            list(range = c(2,7),
                 label = 'Number of Projects', values = ~number_project),
            list(range = c(96,310),
                 label = 'Average Monthly Hours', values = ~average_montly_hours)
            )
          )
fig
```

```{r}
d_wide <- hr %>% 
  group_by(department) %>% 
  summarize_all(mean) 

fig <- d_wide %>% 
  plot_ly(type = 'parcoords',
          line = list(color = ~department),
          dimensions = list(
            list(range = c(0,1),
                 label = 'Job Satisfaction', values = ~satisfaction_level),
            list(range = c(0.36,1),
                 label = 'Last Evaluation', values = ~last_evaluation),
            list(range = c(2,10),
                 label = 'Tenure', values = ~time_spend_company),
            list(range = c(2,7),
                 label = 'Average Monthly Hours', values = ~number_project),
            list(range = c(0,1),
                 label = 'P(leavers)', values = ~left)
            )
          )
fig



```


```{r}
d_wide <- hr %>% 
  group_by(department) %>% 
  summarize_all(mean)

d_tall <- hr %>% 
  group_by(department) %>% 
  summarize_all(mean) %>% 
  gather(variable, value, -department)

d_wide <- d_wide %>% 
  mutate(department = fct_reorder(department, satisfaction_level))

ggplot(d_wide, aes(x = satisfaction_level, y = department)) +
  geom_point()


d_tall <- hr %>% 
  group_by(department) %>% 
  summarize_all(mean) %>% 
  gather(variable, value, -department) %>% 
  filter(variable %in% c('satisfaction_level', 'last_evaluation'))

ggplot(d_tall, aes(x = value, y = department, color = variable)) +
  geom_point()

```

## GGplot Radar chart

```{r}
d <- hr %>% 
  mutate(satisfaction_level = scales::rescale(satisfaction_level),
         last_evaluation = scales::rescale(last_evaluation),
         number_project = scales::rescale(number_project),
         average_montly_hours = scales::rescale(average_montly_hours),
         time_spend_company = scales::rescale(time_spend_company)) %>% 
  group_by(left) %>% 
  summarize(satisfaction_level = mean(satisfaction_level),
            last_evaluation = mean(last_evaluation),
            number_project = mean(number_project),
            average_montly_hours = mean(average_montly_hours),
            time_spend_company = mean(time_spend_company),
            promotion_last_5years = mean(promotion_last_5years)) %>% 
  mutate(left = ifelse(left == 1, 'Left', 'Stayed'))

# d_max <- hr %>% 
#   select(one_of(c('satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company'))) %>% 
#   summarize_all(max) %>% 
#   mutate(left = 'max')
# d_min <- hr %>% 
#   select(one_of(c('satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company'))) %>% 
#   summarize_all(min) %>% 
#   mutate(left = 'min')
# 
# d <- bind_rows(d_max, d_min, d) %>% 
#   as.data.frame

d <- d %>% 
  gather("variable", "value", -left)

ggplot(d) +
  geom_line(aes(x = variable, y = value, group = left)) +
  coord_polar()

# devtools::install_github("ricardo-bion/ggradar", 
#                           dependencies = TRUE)

library(ggradar)

mtcars_radar <- mtcars %>% 
  as_tibble(rownames = "group") %>% 
  mutate_at(vars(-group), scales::rescale) %>% 
  tail(4) %>% 
  select(1:10)

```

```{r}
#high satisfaction levels (>0.6), medium (0.6 > x > 0.4) and low (< 0.4) satisfaction level instead of left vs stayed. 
d <- hr %>% 
  mutate(sat_fac = case_when(satisfaction_level <= 0.4 ~ "low",
                             satisfaction_level > 0.4 & satisfaction_level <= 0.6 ~ 'medium',
                             satisfaction_level > 0.6 ~ 'high')) %>% 
  mutate(sat_fac = factor(sat_fac, levels = c('low', 'medium', 'high'))) %>% 
  group_by(sat_fac) %>% 
  summarize(`Recent Promotion` = mean(promotion_last_5years),
            Turnover = mean(left),
            `Last Evaluation` = mean(last_evaluation),
            `Number of Projects` = mean(number_project),
            `Average Monthly Hours` = mean(average_montly_hours),
            Tenure = mean(time_spend_company)) %>% 
  gather("variable", "value", -sat_fac)

ggplot(d, aes(x = sat_fac, y = value, fill = sat_fac)) +
  geom_bar(stat = 'identity', width = 0.5) +
  scale_fill_brewer("Satisfaction Level", type = 'qual', palette = 2) +
  coord_flip() +
  facet_wrap(~ variable, ncol = 1, scales = 'free') +
  labs(x = '', y = '') +
  theme_minimal() +
  theme(legend.position = 'top')
```

```{r}
library(ggridges)

d <- hr %>% 
  mutate(sat_fac = case_when(satisfaction_level <= 0.4 ~ "low",
                             satisfaction_level > 0.4 & satisfaction_level <= 0.6 ~ 'medium',
                             satisfaction_level > 0.6 ~ 'high')) %>% 
  mutate(sat_fac = factor(sat_fac, levels = c('low', 'medium', 'high'))) %>% 
  select(sat_fac, `Average Montly Hours` = average_montly_hours, 
         `Last Evaluation` = last_evaluation, 
         `Number of Projects` = number_project, Tenure = time_spend_company) %>% 
  mutate_at(vars(-sat_fac), scales::rescale) %>% 
  gather("variable", "value", -sat_fac)

ggplot(d, aes(x = value, y = variable, fill = sat_fac)) +
  geom_density_ridges(alpha = 0.6, color = 'white') +
  scale_fill_brewer("Satisfaction", type = 'qual', palette = 2) +
  labs(title = "", x = "", y = "") +
  theme_ridges() + 
  theme(legend.position = "top")

```








